"""
The full pre-built control library: ~20 audit domains, each with a set of
controls, their audit procedure, and the source tables required to test them.

This is reference data, not organization data — it ships with the platform
so a client never has to type a control in by hand. An organization instead
browses this list and "activates" the controls relevant to them (see
app/services/control_service.py::activate_control_from_library).

Each entry: (domain, control_code, control_name, audit_procedure, required_tables)
"""

CONTROL_LIBRARY: list[tuple[str, str, str, str, list[str]]] = [
    # 1. User Access Management
    ("User Access Management", "AC-001", "User access must be approved",
     "Compare active system users against approved access requests",
     ["hr_employees", "system_users", "access_requests"]),
    ("User Access Management", "AC-002", "Terminated employees must have access removed",
     "Compare terminated employees against active system users",
     ["hr_employees", "system_users"]),
    ("User Access Management", "AC-003", "Dormant accounts must be disabled",
     "Identify active accounts with no login for defined period",
     ["system_users", "login_history"]),
    ("User Access Management", "AC-004", "Users must belong to valid employees",
     "Match system users to HR employee master",
     ["system_users", "hr_employees"]),
    ("User Access Management", "AC-005", "Privileged access must be authorised",
     "Identify users with administrator/privileged roles and verify approval",
     ["system_users", "user_roles", "roles", "access_requests"]),
    ("User Access Management", "AC-006", "Periodic access reviews must occur",
     "Identify users whose access has not been reviewed",
     ["system_users", "access_reviews"]),
    ("User Access Management", "AC-007", "Access changes must be approved",
     "Compare role changes against approved requests",
     ["user_access_changes", "access_requests"]),
    ("User Access Management", "AC-008", "Shared accounts should be restricted",
     "Identify accounts used by multiple people",
     ["system_users", "login_history"]),
    ("User Access Management", "AC-009", "Generic accounts must be identified",
     "Identify generic/shared usernames",
     ["system_users"]),
    ("User Access Management", "AC-010", "Inactive employees should not have active access",
     "Compare employment status to account status",
     ["hr_employees", "system_users"]),

    # 2. Segregation of Duties
    ("Segregation of Duties", "SOD-001", "Supplier creation and payment should be segregated",
     "Identify users able to create suppliers and make payments",
     ["system_users", "user_roles", "role_permissions", "suppliers", "payments"]),
    ("Segregation of Duties", "SOD-002", "PO creation and approval should be segregated",
     "Compare PO creator and approver",
     ["purchase_orders", "po_approvals", "system_users"]),
    ("Segregation of Duties", "SOD-003", "Invoice creation and payment should be segregated",
     "Compare invoice processor and payment processor",
     ["supplier_invoices", "payments", "system_users"]),
    ("Segregation of Duties", "SOD-004", "Journal preparation and approval should be segregated",
     "Compare journal preparer and approver",
     ["journal_entries", "journal_approvals", "system_users"]),
    ("Segregation of Duties", "SOD-005", "Employee creation and payroll processing should be segregated",
     "Compare employee administrator and payroll processor",
     ["hr_employees", "payroll", "system_users"]),
    ("Segregation of Duties", "SOD-006", "Customer creation and credit approval should be segregated",
     "Compare customer creator and credit approver",
     ["customers", "credit_approvals", "system_users"]),
    ("Segregation of Duties", "SOD-007", "Identify conflicting roles",
     "Compare user roles against predefined SoD conflict matrix",
     ["users", "user_roles", "roles", "sod_rules"]),

    # 3. Procure-to-Pay
    ("Procure-to-Pay", "PR-001", "POs require approval",
     "Identify POs without required approval",
     ["purchase_orders", "po_approvals"]),
    ("Procure-to-Pay", "PR-002", "Approval limits must be respected",
     "Compare PO value to approver authority",
     ["purchase_orders", "po_approvals", "approval_limits", "user_roles"]),
    ("Procure-to-Pay", "PR-003", "POs must be issued to approved suppliers",
     "Match PO suppliers to supplier master",
     ["purchase_orders", "suppliers"]),
    ("Procure-to-Pay", "PR-004", "POs should precede purchases",
     "Identify invoices without POs",
     ["purchase_orders", "supplier_invoices"]),
    ("Procure-to-Pay", "PR-005", "Duplicate POs should be identified",
     "Identify duplicate PO numbers",
     ["purchase_orders"]),
    ("Procure-to-Pay", "PR-006", "Duplicate invoices must be prevented",
     "Identify duplicate supplier + invoice number",
     ["supplier_invoices", "suppliers"]),
    ("Procure-to-Pay", "PR-007", "Invoice must reference valid supplier",
     "Match invoice supplier to supplier master",
     ["supplier_invoices", "suppliers"]),
    ("Procure-to-Pay", "PR-008", "Invoice should match PO",
     "Compare invoice to PO",
     ["supplier_invoices", "purchase_orders"]),
    ("Procure-to-Pay", "PR-009", "Invoice should match goods received",
     "Compare invoice quantity to GRN",
     ["supplier_invoices", "goods_receipts"]),
    ("Procure-to-Pay", "PR-010", "Invoice approval is required",
     "Identify invoices without approval",
     ["supplier_invoices", "invoice_approvals"]),
    ("Procure-to-Pay", "PR-011", "Three-way match must be performed",
     "Compare PO, GRN and invoice",
     ["purchase_orders", "goods_receipts", "supplier_invoices"]),
    ("Procure-to-Pay", "PR-012", "Invoice quantity should not exceed receipt",
     "Compare invoice quantity to received quantity",
     ["supplier_invoices", "goods_receipts"]),
    ("Procure-to-Pay", "PR-013", "Invoice price should agree to PO",
     "Compare invoice price to PO price",
     ["supplier_invoices", "purchase_orders"]),
    ("Procure-to-Pay", "PR-014", "Payment should not occur before receipt",
     "Identify payments without GRN",
     ["payments", "goods_receipts", "supplier_invoices"]),
    ("Procure-to-Pay", "PR-015", "Payments require approval",
     "Identify payments without approval",
     ["payments", "payment_approvals"]),
    ("Procure-to-Pay", "PR-016", "Payments should only be made to approved suppliers",
     "Match payments to supplier master",
     ["payments", "suppliers"]),
    ("Procure-to-Pay", "PR-017", "Duplicate payments must be prevented",
     "Identify duplicate payments",
     ["payments", "supplier_invoices"]),
    ("Procure-to-Pay", "PR-018", "Payment amount should agree to invoice",
     "Compare payment to invoice",
     ["payments", "supplier_invoices"]),
    ("Procure-to-Pay", "PR-019", "High-value payments require additional approval",
     "Identify payments exceeding thresholds",
     ["payments", "payment_approvals", "approval_limits", "user_roles"]),
    ("Procure-to-Pay", "PR-020", "Payments to inactive suppliers should be investigated",
     "Match payment to supplier status",
     ["payments", "suppliers"]),

    # 4. Financial Transactions / General Ledger
    ("Financial Transactions / General Ledger", "GL-001", "Journal entries require approval",
     "Identify unapproved journals",
     ["journal_entries", "journal_approvals"]),
    ("Financial Transactions / General Ledger", "GL-002", "Journals must be posted by authorised users",
     "Compare preparer to user access",
     ["journal_entries", "system_users", "user_roles"]),
    ("Financial Transactions / General Ledger", "GL-003", "Manual journals require review",
     "Identify manual journal entries",
     ["journal_entries"]),
    ("Financial Transactions / General Ledger", "GL-004", "Journals posted after period-end require review",
     "Identify late journals",
     ["journal_entries", "accounting_periods"]),
    ("Financial Transactions / General Ledger", "GL-005", "Duplicate journals should be identified",
     "Search for duplicate journal patterns",
     ["journal_entries"]),
    ("Financial Transactions / General Ledger", "GL-006", "Unusual journals should be investigated",
     "Apply amount/date/account/user rules",
     ["journal_entries"]),
    ("Financial Transactions / General Ledger", "GL-007", "Journals above threshold require approval",
     "Compare journal amount to approval threshold",
     ["journal_entries", "journal_approvals", "approval_limits", "user_roles"]),
    ("Financial Transactions / General Ledger", "GL-008", "Suspense accounts require review",
     "Identify unresolved suspense balances",
     ["journal_entries", "general_ledger"]),
    ("Financial Transactions / General Ledger", "GL-009", "Debits and credits must balance",
     "Test journal-level balance",
     ["journal_entries", "journal_lines"]),
    ("Financial Transactions / General Ledger", "GL-010", "GL should reconcile to subledger",
     "Reconcile GL to AP/AR/inventory/payroll",
     ["general_ledger", "ap_transactions", "ar_transactions", "inventory", "payroll"]),

    # 5. Payroll
    ("Payroll", "PY-001", "Only valid employees should be paid",
     "Match payroll employees to HR master",
     ["payroll", "hr_employees"]),
    ("Payroll", "PY-002", "Terminated employees should not be paid",
     "Compare termination dates to payroll",
     ["payroll", "hr_employees"]),
    ("Payroll", "PY-003", "Employee additions require approval",
     "Compare new employees to approvals",
     ["hr_employees", "employee_approvals"]),
    ("Payroll", "PY-004", "Salary changes require approval",
     "Compare salary changes to approvals",
     ["salary_changes", "salary_approvals"]),
    ("Payroll", "PY-005", "Duplicate employees should be identified",
     "Search duplicate IDs/names/bank accounts",
     ["hr_employees"]),
    ("Payroll", "PY-006", "Duplicate bank accounts should be investigated",
     "Identify multiple employees sharing accounts",
     ["hr_employees", "bank_accounts"]),
    ("Payroll", "PY-007", "Payroll should agree to HR master",
     "Reconcile payroll population",
     ["payroll", "hr_employees"]),
    ("Payroll", "PY-008", "Unusual salary increases should be investigated",
     "Compare current vs prior salary",
     ["payroll_history", "hr_employees"]),
    ("Payroll", "PY-009", "Ghost employees should be identified",
     "Detect employees with no supporting HR information",
     ["hr_employees", "payroll", "employee_documents"]),
    ("Payroll", "PY-010", "Payroll changes should be logged",
     "Compare changes to audit logs",
     ["payroll_changes", "audit_logs"]),

    # 6. Master Data Management
    ("Master Data Management", "MD-001", "Supplier creation requires approval",
     "Compare suppliers to approvals",
     ["suppliers", "supplier_approvals"]),
    ("Master Data Management", "MD-002", "Duplicate suppliers should be prevented",
     "Identify duplicate registration/bank/tax numbers",
     ["suppliers"]),
    ("Master Data Management", "MD-003", "Supplier bank changes require approval",
     "Compare bank changes to approvals",
     ["suppliers", "supplier_bank_changes", "approvals"]),
    ("Master Data Management", "MD-004", "Inactive suppliers should not receive payments",
     "Compare supplier status to payments",
     ["suppliers", "payments"]),
    ("Master Data Management", "MD-005", "Supplier master changes must be logged",
     "Compare changes to audit logs",
     ["suppliers", "audit_logs"]),
    ("Master Data Management", "MD-006", "Customer creation requires approval",
     "Compare customers to approvals",
     ["customers", "customer_approvals"]),
    ("Master Data Management", "MD-007", "Duplicate customers should be identified",
     "Identify duplicate IDs/tax numbers",
     ["customers"]),
    ("Master Data Management", "MD-008", "Credit limits require approval",
     "Compare credit limit changes",
     ["customers", "credit_approvals"]),
    ("Master Data Management", "MD-009", "Inactive customers should not transact",
     "Compare customer status to transactions",
     ["customers", "sales_orders"]),

    # 7. Order-to-Cash
    ("Order-to-Cash", "OTC-001", "Sales orders require approval",
     "Identify unapproved sales orders",
     ["sales_orders", "sales_approvals"]),
    ("Order-to-Cash", "OTC-002", "Customers must be valid",
     "Match sales orders to customer master",
     ["sales_orders", "customers"]),
    ("Order-to-Cash", "OTC-003", "Credit limits must be respected",
     "Compare order value to credit limit",
     ["sales_orders", "customers"]),
    ("Order-to-Cash", "OTC-004", "Invoice should follow delivery",
     "Identify invoices without delivery",
     ["sales_invoices", "deliveries"]),
    ("Order-to-Cash", "OTC-005", "Duplicate invoices should be prevented",
     "Identify duplicate invoices",
     ["sales_invoices"]),
    ("Order-to-Cash", "OTC-006", "Discounts require approval",
     "Identify discounts above threshold",
     ["sales_orders", "discount_approvals"]),
    ("Order-to-Cash", "OTC-007", "Receipts should be allocated",
     "Identify unallocated receipts",
     ["customer_receipts", "sales_invoices"]),
    ("Order-to-Cash", "OTC-008", "Bad debts should be monitored",
     "Identify overdue customer balances",
     ["receivables", "customers"]),

    # 8. Change Management
    ("Change Management", "CM-001", "Changes require approval",
     "Compare production changes to approved requests",
     ["change_requests", "change_approvals", "production_changes"]),
    ("Change Management", "CM-002", "Changes must be tested",
     "Identify changes without testing evidence",
     ["change_requests", "test_results"]),
    ("Change Management", "CM-003", "Emergency changes require retrospective approval",
     "Identify emergency changes without approval",
     ["production_changes", "change_approvals"]),
    ("Change Management", "CM-004", "Developer/deployer segregation",
     "Compare developer and deployment user",
     ["code_changes", "deployments", "system_users"]),
    ("Change Management", "CM-005", "Production changes must be logged",
     "Reconcile production changes to change records",
     ["production_changes", "change_requests"]),
    ("Change Management", "CM-006", "Changes outside approved window require review",
     "Identify unusual deployment times",
     ["deployments", "change_requests"]),
    ("Change Management", "CM-007", "Unauthorised changes must be identified",
     "Compare production logs to approved changes",
     ["production_logs", "change_requests"]),

    # 9. IT Operations
    ("IT Operations", "OP-001", "Critical jobs must execute successfully",
     "Identify failed jobs",
     ["scheduled_jobs", "job_executions"]),
    ("IT Operations", "OP-002", "Failed jobs must be investigated",
     "Identify unresolved failures",
     ["job_executions", "incident_records"]),
    ("IT Operations", "OP-003", "Critical jobs must run according to schedule",
     "Identify missed executions",
     ["scheduled_jobs", "job_executions"]),
    ("IT Operations", "OP-004", "Processing time should remain within limits",
     "Identify abnormal execution times",
     ["job_executions", "scheduled_jobs"]),
    ("IT Operations", "OP-005", "System incidents must be logged",
     "Compare incidents to system logs",
     ["incidents", "system_logs"]),
    ("IT Operations", "OP-006", "Critical incidents require resolution",
     "Identify overdue incidents",
     ["incidents"]),
    ("IT Operations", "OP-007", "Logs must be retained",
     "Identify missing/expired logs",
     ["system_logs", "log_retention_rules"]),

    # 10. Backup & Recovery
    ("Backup & Recovery", "BK-001", "Critical systems must be backed up",
     "Identify systems without backup records",
     ["systems", "backup_jobs"]),
    ("Backup & Recovery", "BK-002", "Backups must run according to schedule",
     "Identify missed backups",
     ["backup_schedules", "backup_jobs"]),
    ("Backup & Recovery", "BK-003", "Failed backups must be investigated",
     "Identify failed backup jobs",
     ["backup_jobs", "backup_incidents"]),
    ("Backup & Recovery", "BK-004", "Backup retention requirements must be met",
     "Test backup age/retention",
     ["backup_jobs", "backup_retention_rules"]),
    ("Backup & Recovery", "BK-005", "Recovery testing must occur",
     "Identify systems without recent recovery tests",
     ["systems", "recovery_tests"]),
    ("Backup & Recovery", "BK-006", "Recovery tests must pass",
     "Identify failed recovery tests",
     ["recovery_tests"]),

    # 11. IT Asset Management
    ("IT Asset Management", "AS-001", "IT assets must be recorded",
     "Identify assets missing from register",
     ["asset_register", "system_inventory"]),
    ("IT Asset Management", "AS-002", "Assigned assets must belong to valid employees",
     "Compare asset assignments to HR",
     ["asset_register", "hr_employees"]),
    ("IT Asset Management", "AS-003", "Terminated employees must return assets",
     "Compare termination list to asset assignments",
     ["hr_employees", "asset_register"]),
    ("IT Asset Management", "AS-004", "Unauthorised software should be identified",
     "Compare installed software to approved software",
     ["asset_register", "software_inventory", "approved_software"]),
    ("IT Asset Management", "AS-005", "Unsupported systems should be identified",
     "Compare versions to support matrix",
     ["system_inventory", "support_matrix"]),

    # 12. Data Privacy
    ("Data Privacy", "DP-001", "Access to personal information must be authorised",
     "Compare users with access rights",
     ["users", "data_access", "roles"]),
    ("Data Privacy", "DP-002", "Sensitive data access must be logged",
     "Identify access without logs",
     ["data_access", "audit_logs"]),
    ("Data Privacy", "DP-003", "Personal information should not be unnecessarily exposed",
     "Identify excessive access",
     ["data_classification", "user_access"]),
    ("Data Privacy", "DP-004", "Data retention requirements must be followed",
     "Identify records beyond retention period",
     ["data_records", "retention_rules"]),
    ("Data Privacy", "DP-005", "Data deletion requests should be processed",
     "Compare requests to deletion records",
     ["privacy_requests", "deletion_records"]),

    # 13. Encryption Controls
    ("Encryption Controls", "EN-001", "Sensitive data must be encrypted",
     "Identify sensitive datasets without encryption",
     ["data_assets", "encryption_config"]),
    ("Encryption Controls", "EN-002", "Encryption keys must be managed",
     "Identify expired/unauthorised keys",
     ["encryption_keys", "key_management_logs"]),
    ("Encryption Controls", "EN-003", "TLS certificates must be valid",
     "Identify certificates approaching expiry",
     ["certificates", "systems"]),
    ("Encryption Controls", "EN-004", "Weak encryption protocols must be identified",
     "Compare configurations against approved standards",
     ["system_configurations", "security_baselines"]),

    # 14. Certificate Management
    ("Certificate Management", "CERT-001", "Certificates must not expire unexpectedly",
     "Identify certificates expiring within threshold",
     ["certificates"]),
    ("Certificate Management", "CERT-002", "Expired certificates must be identified",
     "Identify expired certificates",
     ["certificates"]),
    ("Certificate Management", "CERT-003", "Certificates must belong to authorised systems",
     "Compare certificates to system inventory",
     ["certificates", "systems"]),
    ("Certificate Management", "CERT-004", "Certificate renewals must be tracked",
     "Identify certificates without renewal records",
     ["certificates", "certificate_renewals"]),

    # 15. API Controls
    ("API Controls", "API-001", "APIs must be registered",
     "Identify unregistered APIs",
     ["api_inventory", "systems"]),
    ("API Controls", "API-002", "API access must be authorised",
     "Compare API consumers to permissions",
     ["api_access", "users", "roles"]),
    ("API Controls", "API-003", "Failed API authentication should be monitored",
     "Identify unusual failed requests",
     ["api_logs"]),
    ("API Controls", "API-004", "Sensitive APIs must use encryption",
     "Identify APIs without TLS",
     ["api_inventory", "api_configurations"]),
    ("API Controls", "API-005", "API keys should expire",
     "Identify expired/old API keys",
     ["api_keys"]),

    # 16. Vulnerability Management
    ("Vulnerability Management", "VM-001", "Vulnerabilities must be identified",
     "Import vulnerability scan results",
     ["vulnerabilities", "assets"]),
    ("Vulnerability Management", "VM-002", "Critical vulnerabilities must be remediated within SLA",
     "Compare severity/date against SLA",
     ["vulnerabilities", "remediation_actions", "sla_rules"]),
    ("Vulnerability Management", "VM-003", "Unsupported systems must be identified",
     "Compare assets to support matrix",
     ["assets", "software_inventory", "support_matrix"]),
    ("Vulnerability Management", "VM-004", "Vulnerability remediation must be retested",
     "Compare remediation to retest results",
     ["vulnerabilities", "remediation_actions", "retests"]),

    # 17. Network Controls
    ("Network Controls", "NW-001", "Unauthorised network connections should be identified",
     "Compare connections to approved inventory",
     ["network_connections", "approved_connections"]),
    ("Network Controls", "NW-002", "Firewall rules require approval",
     "Identify unapproved rules",
     ["firewall_rules", "firewall_approvals"]),
    ("Network Controls", "NW-003", "Excessively permissive firewall rules should be identified",
     "Test rules against baseline",
     ["firewall_rules", "security_baselines"]),
    ("Network Controls", "NW-004", "Network devices must be inventoried",
     "Compare discovered devices to inventory",
     ["network_devices", "asset_register"]),

    # 18. Web Filtering / Content Security
    ("Web Filtering / Content Security", "WF-001", "Web filtering must be active on all endpoints",
     "Compare endpoint filtering agent status against asset register",
     ["asset_register", "web_filter_status"]),
    ("Web Filtering / Content Security", "WF-002", "Malicious/blacklisted categories must be blocked by policy",
     "Compare filter policy configuration against approved category baseline",
     ["web_filter_policies", "security_baselines"]),
    ("Web Filtering / Content Security", "WF-003", "Blocked access attempts must be logged",
     "Identify blocked events missing from the log",
     ["web_filter_logs", "security_logs"]),
    ("Web Filtering / Content Security", "WF-004", "Repeated attempts to access malicious sites should be investigated",
     "Identify users with abnormal frequency of blocked/flagged attempts",
     ["web_filter_logs", "users"]),
    ("Web Filtering / Content Security", "WF-005", "Filtering policy exceptions/overrides require approval",
     "Compare granted exceptions to approval records",
     ["web_filter_exceptions", "exception_approvals"]),
    ("Web Filtering / Content Security", "WF-006", "Filtering must apply consistently on and off the corporate network",
     "Compare policy enforcement status for on-network vs. remote/roaming devices",
     ["web_filter_status", "remote_access_logs"]),
    ("Web Filtering / Content Security", "WF-007", "Newly categorised/emerging threat domains must be updated within SLA",
     "Compare filter category database version/update timestamp against vendor release",
     ["web_filter_config", "patch_releases"]),
    ("Web Filtering / Content Security", "WF-008", "Endpoints must not have unauthorised filtering bypass/proxy tools",
     "Compare installed software against a list of known bypass/VPN/proxy tools",
     ["software_inventory", "approved_software"]),
    ("Web Filtering / Content Security", "WF-009", "HTTPS/TLS inspection (where enabled) must be correctly configured",
     "Compare TLS inspection certificate and scope configuration to policy",
     ["web_filter_config", "certificates"]),
    ("Web Filtering / Content Security", "WF-010", "Filtering coverage must extend to all managed devices",
     "Compare devices with active agent/filtering against total managed device count",
     ["asset_register", "web_filter_status"]),

    # 19. Patch Management
    ("Patch Management", "PM-001", "Critical security patches must be applied within SLA",
     "Compare patch release date + severity against installation date",
     ["patch_inventory", "patch_releases", "sla_rules"]),
    ("Patch Management", "PM-002", "Unpatched systems must be identified",
     "Compare installed patch levels against available/required patches",
     ["asset_register", "patch_inventory", "patch_catalogue"]),
    ("Patch Management", "PM-003", "End-of-life/unsupported systems must be flagged",
     "Compare OS/software versions against vendor support matrix",
     ["system_inventory", "support_matrix"]),
    ("Patch Management", "PM-004", "Patch deployment must be approved",
     "Compare deployed patches to change/patch approval records",
     ["patch_deployments", "patch_approvals"]),
    ("Patch Management", "PM-005", "Patch testing must occur before production deployment",
     "Identify patches deployed without test evidence",
     ["patch_deployments", "test_results"]),
    ("Patch Management", "PM-006", "Emergency patches require retrospective approval",
     "Identify emergency patches without follow-up approval",
     ["patch_deployments", "patch_approvals"]),
    ("Patch Management", "PM-007", "Failed patch deployments must be investigated",
     "Identify patches that failed to install and remain unresolved",
     ["patch_deployments", "patch_incidents"]),
    ("Patch Management", "PM-008", "Patch compliance must be reconciled per device",
     "Compare required vs. installed patches per asset",
     ["asset_register", "patch_inventory", "patch_catalogue"]),
    ("Patch Management", "PM-009", "Third-party/application patches must be tracked, not just OS",
     "Compare application version against vendor patch releases",
     ["software_inventory", "patch_releases"]),
    ("Patch Management", "PM-010", "Patch exceptions/deferrals require documented justification",
     "Identify systems excluded from patching without an approved exception",
     ["patch_exceptions", "exception_approvals"]),

    # 20. Remote Access Testing
    ("Remote Access", "RA-001", "Remote access must require MFA",
     "Identify remote sessions/accounts without MFA enforced",
     ["remote_access_logs", "mfa_config", "system_users"]),
    ("Remote Access", "RA-002", "Remote access must be explicitly authorised",
     "Compare active remote access grants against approval records",
     ["remote_access_grants", "access_requests"]),
    ("Remote Access", "RA-003", "VPN access must be restricted to approved users",
     "Match VPN account list to approved user/employee list",
     ["vpn_accounts", "hr_employees", "access_requests"]),
    ("Remote Access", "RA-004", "Terminated employees must have remote access revoked",
     "Compare termination list to active VPN/remote sessions",
     ["hr_employees", "system_users", "vpn_accounts", "remote_access_logs"]),
    ("Remote Access", "RA-005", "Remote sessions must be logged",
     "Identify remote access without corresponding session logs",
     ["remote_access_logs", "session_audit"]),
    ("Remote Access", "RA-006", "Remote access outside approved hours/geography should be reviewed",
     "Apply time/geo rules to session logs",
     ["remote_access_logs", "access_policies"]),
    ("Remote Access", "RA-007", "Privileged remote access requires additional approval",
     "Identify privileged remote sessions without elevated approval",
     ["remote_access_logs", "user_roles", "privileged_access_approvals"]),
    ("Remote Access", "RA-008", "Third-party/vendor remote access must be time-bound and logged",
     "Compare vendor access grants to defined access windows",
     ["vendor_access_grants", "remote_access_logs"]),
    ("Remote Access", "RA-009", "Remote access tools must be from an approved catalogue",
     "Compare tools in use (RDP, TeamViewer, AnyDesk, etc.) against approved list",
     ["remote_access_tools", "approved_software"]),
    ("Remote Access", "RA-010", "Idle remote sessions must time out",
     "Identify sessions exceeding approved idle duration",
     ["remote_access_logs", "session_policies"]),
    ("Remote Access", "RA-011", "Failed remote login attempts must be monitored",
     "Identify unusual patterns of failed remote authentication",
     ["remote_access_logs", "login_history"]),
    ("Remote Access", "RA-012", "Split-tunnelling / unauthorised network bridging should be identified",
     "Compare VPN configuration to approved network policy",
     ["vpn_config", "network_policies"]),
]

# Sensible defaults applied to every activated control — the client can
# still edit type/nature/frequency after activation via the normal control
# edit flow, this just avoids forcing them to pick blindly on day one.
DEFAULT_CONTROL_TYPE = "detective"
DEFAULT_CONTROL_NATURE = "automated"
DEFAULT_CONTROL_FREQUENCY = "continuous"
